### ISSUE TITLE
Non-distributed usage, parallelization

### ISSUE THREAD

**Issue by j8asic** [optimad/PABLO#4]
Hi, very nice project!
Did you maybe plan to optionally remove dependency on MPI? Maybe local usage for a problem is enough; or also the trend is that MPI communication is on higher level to employ distributed + some other local parallelization method.
That being said, maybe employing direct cores parallelization (OpenMP, TBB, whatever) for some stuff that can be parallelized?
Best regards,
Josip

**Comment by edoardolombardi** [comment]
Hi Josip,
Thank you so much.
Yes, we plan to give the users the option to use PABLO without MPI as soon as possible.
On the other hand, we didn't schedule any hybrid parallel implementation at the moment. We would like to have a stable MPI version first.
But in the next future we aim to give PABLO as many features as we can.
In any case we would be glad to follow a fork of PABLO about this and we ready to discuss with anyone wants to develop PABLO in that direction or to expand other features.
If you start to test, use or working on our library, please let us know any problem or bug that you observe.
Finally, some basic tutorial codes are included in the repository; please, find the results obtained by the tutorials in PABLO github pages ( http://optimad.github.io/PABLO/ ).
Best,

Edoardo

**Comment by j8asic** [comment]
Thanks for the information. I'll probably need smoothly working distributed octree in some months from now, so I'll keep an eye on the project and in future contribute if needed.
BR

**Comment by edoardolombardi** [comment]
Thank you. Every contribution is welcome!
