### ISSUE TITLE
Paired balancing

### ISSUE THREAD

**Issue by j8asic** [optimad/PABLO#5]
Hi,
just for the sake of record, I'll leave here my wish:

Some solving and meshing algorithms need (or simply give better results if) octants to be not only balanced, but also paired-up. It means that if an octant's son is to be split, its brothers (octants belonging to the same father element) should be split along with it. It would be nice if balancing could obey that simple additional criteria.

Best regards,
Josip

**Comment by edoardolombardi** [comment]
Hi Josip,

If I understood you're talking about a sort of patch with uniform refinement. For the moment you can do it a priori by setting a marker of an element >1. However, if you want to refine during an adaption an element and every its brothers (or elements deriving from a same selected ancestor) for now is not possible to do in an automatic way with a PABLO feature. We'll keep in mind your need and at the earliest possibility we'll try to implement the new feature in the library. 
Eventually, if you need it immediately we can discuss about the possibility to realize this kind of refinement outside PABLO, by imposing some refinement criteria ad hoc for the purpose. Let us know if you need support, you can send me a private mail or join the PABLO google user group at https://groups.google.com/forum/#!forum/pablo-users. 

Thank you again, every request is useful to enrich PABLO and its usability !

Best,

Edoardo
